substitutions:
  friendly_name: P1 Interface

esphome:
  name: p1-interface
  friendly_name: ${friendly_name}

esp8266:
  board: esp12e

# Enable logging
logger:
  # Serial logging is disabled by setting the logger baud rate to 0.
  # Otherwise the logger will occupy the hardware UART, making it unavailable
  # for receiving smart meter data on pin D7 (GPIO13).
  baud_rate: 0
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.121.3.125

i2c:
  sda: GPIO4
  scl: GPIO5

uart:
  rx_pin: GPIO13
  baud_rate: 115200
  rx_buffer_size: 1700
#  debug:
#    direction: RX
#    dummy_receiver: false
#    after:
#      timeout: 1000ms
#    sequence:
#      - lambda: UARTDebug::log_string(direction, bytes);

dsmr:
  request_pin: GPIO14
  request_interval: 10s
  max_telegram_length: 1700

text_sensor:
  - platform: dsmr
    identification:
      name: ${friendly_name} Identification
#    p1_version:
#      name: ${friendly_name} Version
    electricity_tariff: 
      name: ${friendly_name} Tariff
#    telegram:
#      name: ${friendly_name} Raw Telegram

sensor:
  - platform: htu21d
    model: HTU21D
    temperature: 
      name: ${friendly_name} Temperature
    humidity: 
      name: ${friendly_name} Humidity
    heater: 
      name: ${friendly_name} HTU21D Heater
  - platform: adc
    pin: VCC
    name: "VCC Voltage"
  - platform: dsmr
    energy_delivered_tariff1:
      name: ${friendly_name} Energy Delivered Tariff 1
      state_class: total_increasing
    energy_delivered_tariff2:
      name: ${friendly_name} Energy Delivered Tariff 2
      state_class: total_increasing
    energy_returned_tariff1:
      name: ${friendly_name} Energy Returned Tariff 1
    energy_returned_tariff2:
      name: ${friendly_name} Energy Returned Tariff 2
    power_delivered:
      name: ${friendly_name} Power Consumed
    power_returned:
      name: ${friendly_name} Power Returned
#    electricity_failures:
#      name: ${friendly_name} Electricity Failures
#    electricity_long_failures:
#      name: ${friendly_name} Electricity Long Failures
    voltage_l1:
      name: ${friendly_name} Voltage L1
    voltage_l2:
      name: ${friendly_name} Voltage L2
    voltage_l3:
      name: ${friendly_name} Voltage L3
    current_l1:
      name: ${friendly_name} Current L1
    current_l2:
      name: ${friendly_name} Current L2
    current_l3:
      name: ${friendly_name} Current L3
    power_delivered_l1:
      name: ${friendly_name} Power Delivered L1
    power_delivered_l2:
      name: ${friendly_name} Power Delivered L2
    power_delivered_l3:
      name: ${friendly_name} Power Delivered L3
    power_returned_l1:
      name: ${friendly_name} Power Returned L1
    power_returned_l2:
      name: ${friendly_name} Power Returned L2
    power_returned_l3:
      name: ${friendly_name} Power Returned L3
